export default function CollaborativeSpirit() {
  return (
    <article className="max-w-3xl mx-auto px-4 py-12 space-y-4">
      <h1 className="text-3xl font-bold text-heading">Esprit collaboratif</h1>
      <h2 className="text-2xl font-semibold text-heading mt-8">Ma définition</h2>
      <p className="text-body leading-relaxed">L'esprit collaboratif, c'est la capacité à travailler au sein d'une équipe en participant activement à un projet commun, avec l'envie sincère de le faire avancer. Ce n'est pas seulement « faire sa part » : c'est s'impliquer dans la réussite collective, partager ses idées, s'intéresser au travail des autres et contribuer à un objectif qui dépasse sa contribution individuelle.</p>
      <p className="text-body leading-relaxed">Dans une équipe de développeurs, cet esprit est essentiel car nous travaillons fondamentalement ensemble : les travaux des uns sont systématiquement revus par les autres via les reviews de pull requests, et nous pratiquons parfois le pair coding. Discuter des problèmes rencontrés et des solutions possibles fait partie intégrante du quotidien. Cette compétence est d'ailleurs étroitement liée à la capacité de remise en question : collaborer efficacement suppose de savoir accepter les critiques sur son travail et d'accueillir des points de vue différents sur un sujet technique.</p>
      <p className="text-body leading-relaxed">L'actualité confirme l'importance croissante de cette compétence : le travail produit/tech devient de plus en plus transverse, mêlant business, tech et data. Un article de TechTarget de janvier 2026, [*How enterprise software planning is taking shape for 2026*](https://www.techtarget.com/searcherp/feature/How-enterprise-software-planning-is-taking-shape-for-2026), montre que les décisions logicielles en entreprise soulèvent désormais des questions de responsabilité et d'intégration qui traversent les équipes et les systèmes, notamment avec l'essor de l'IA. L'article souligne par exemple que les responsables des centres de contact ne peuvent plus décider seuls des investissements technologiques, et que les leaders doivent coordonner de nombreuses parties prenantes. Autrement dit, le développeur de 2026 ne travaille plus dans son coin : il collabore avec le produit, le business et la data — l'esprit collaboratif devient une compétence structurante du métier.</p>
      <h2 className="text-2xl font-semibold text-heading mt-8">Mes éléments de preuve</h2>
      <p className="text-body leading-relaxed"><strong>Eco City Guide</strong> est un projet que j'ai réalisé en groupe lors de ma première année de reconversion pour devenir développeuse. Au sein d'une équipe de quatre personnes, nous avons monté un projet de bout en bout : définition des fonctionnalités attendues pour le MVP (Minimum Viable Product), choix des stacks techniques, développement, tests et déploiement.</p>
      <p className="text-body leading-relaxed">Tout au long du projet, l'esprit collaboratif a été mis en œuvre concrètement : nous avons travaillé parfois en pair coding, parfois en développant chacun de notre côté avant de mettre en commun notre travail, ce qui exigeait de se coordonner, de discuter des choix techniques et d'arbitrer collectivement lorsque nos approches divergeaient. Chaque décision structurante — du périmètre du MVP à la stack technique — a été prise en équipe, ce qui nous a obligés à argumenter, écouter et parfois renoncer à nos préférences individuelles au profit du projet.</p>
      <p className="text-body leading-relaxed">Le résultat est là : le projet a été concrétisé et a abouti exactement comme nous le voulions, conformément au MVP que nous avions défini ensemble. Ma valeur ajoutée dans cette réussite a été double : contribuer techniquement au développement, mais aussi entretenir la dynamique de groupe — en participant activement aux mises en commun et en veillant à ce que les décisions restent collectives. C'est cette cohésion qui nous a permis de tenir nos objectifs alors que nous étions tous en début de formation.</p>
      <p className="text-body leading-relaxed">👉 [Lien vers la réalisation : Eco City Guide](#)</p>
      <p className="text-body leading-relaxed">Aujourd'hui, en tant qu'apprenante au sein d'une équipe front en entreprise, je continue de mobiliser cette compétence quotidiennement : je soumets mon travail aux reviews de mes collègues, je participe aux échanges sur les solutions techniques et je m'appuie sur les retours de l'équipe pour améliorer mes contributions — comme le montre par exemple ma réalisation sur la gestion multilingue avec Strapi.</p>
      <p className="text-body leading-relaxed">👉 [Lien vers la réalisation : gestion multilingue des pages avec Strapi](#)</p>
      <h2 className="text-2xl font-semibold text-heading mt-8">Mon autocritique</h2>
      <p className="text-body leading-relaxed"><strong>Niveau de maîtrise.</strong> Je considère bien maîtriser cette compétence. J'aime travailler en équipe, car je suis convaincue que l'intelligence collective permet d'arriver à de belles choses si tout le monde y met du sien.</p>
      <p className="text-body leading-relaxed"><strong>Place dans mon profil.</strong> Cette compétence occupe une place prioritaire dans mon métier de développeuse : le développement en entreprise est par nature un travail collectif, rythmé par les reviews, le pair coding et les échanges techniques. Un développeur qui ne collabore pas prive son équipe — et se prive lui-même — de la richesse des regards croisés.</p>
      <p className="text-body leading-relaxed"><strong>Vitesse d'acquisition.</strong> Je l'ai acquise rapidement, et en réalité bien avant ma reconversion : c'est lors de mes études de droit, à travers les travaux de groupe et les projets communs, que j'ai appris à travailler avec les autres. Cette expérience antérieure m'a permis d'arriver dans le développement avec des réflexes collaboratifs déjà installés.</p>
      <p className="text-body leading-relaxed"><strong>Mon conseil.</strong> Pour acquérir cette compétence, rien de mieux que la pratique : réaliser des sujets et des travaux à plusieurs permet de découvrir ses qualités et ses défauts dans le travail en groupe — et c'est en en prenant conscience que l'on peut s'améliorer.</p>
      <h2 className="text-2xl font-semibold text-heading mt-8">Mon évolution dans cette compétence</h2>
      <p className="text-body leading-relaxed">Je considère cette compétence comme maîtrisée et je n'ai pas de besoin de formation spécifique la concernant. Mon objectif à moyen terme est de continuer à la faire vivre dans un contexte professionnel exigeant : à mesure que je gagnerai en expérience, je souhaite prendre une part plus active dans la collaboration de mon équipe — par exemple en reviewant à mon tour le travail de mes collègues et en contribuant davantage aux discussions d'architecture. Dans un contexte où le travail tech devient de plus en plus transverse, je souhaite également développer ma capacité à collaborer au-delà de mon équipe de développement, avec les profils produit, business et data.</p>
      <h2 className="text-2xl font-semibold text-heading mt-8">Principales réalisations rattachées à cette compétence</h2>
      <p className="text-body leading-relaxed">- [Eco City Guide — projet de groupe réalisé en équipe de 4, de la définition du MVP au déploiement](#)</p>
      <p className="text-body leading-relaxed">- [Gestion multilingue des pages avec le CMS Strapi — collaboration via les reviews de PR au sein de mon équipe front](#)</p>
    </article>
  );
}
