export default function SolutionDevelopment() {
  return (
    <article className="max-w-3xl mx-auto px-4 py-12 space-y-4">
      <h1 className="text-3xl font-bold text-heading">Développement d'une solution</h1>
      <h2 className="text-2xl font-semibold text-heading mt-8">Ma définition</h2>
      <p className="text-body leading-relaxed">Le <strong>développement d'une solution</strong>, c'est la mise en œuvre concrète de ce qui a été imaginé lors de la phase de conception : <strong>développer la solution fonctionnelle</strong> avec les bonnes stacks et les bonnes pratiques. Le but est de mettre en place la solution <strong>telle qu'elle a été conçue</strong>, en veillant à respecter :</p>
      <p className="text-body leading-relaxed">- les <strong>patterns et pratiques du projet</strong> — par exemple, respecter les conventions de nommage en vigueur (comme le *camelCase* pour les constantes) afin de garantir la cohérence du code au sein de l'équipe ;</p>
      <p className="text-body leading-relaxed">- l'utilisation d'un <strong>code actuel</strong>, s'appuyant sur les standards modernes du web et adapté aux principaux moteurs de rendu et navigateurs.</p>
      <p className="text-body leading-relaxed">Mais développer ne s'arrête pas à la première mise en production : cette compétence recouvre aussi le <strong>débogage</strong>, la <strong>correction de bugs</strong> et la <strong>maintenance</strong> de la solution dans le temps. Précisément, il s'agit donc de <strong>développer et maintenir une solution</strong>, ce qui inclut la capacité à identifier les bugs et à les corriger durablement.</p>
      <p className="text-body leading-relaxed">Cette compétence connaît actuellement une mutation profonde : avec l'<strong>automatisation croissante du code via l'IA</strong>, le développeur devient de plus en plus un <strong>« superviseur »</strong> — il génère, relit, valide, corrige et intègre du code produit par des assistants, comme le décrivent [les tendances tech du développement pour 2026](https://www.idlen.io/fr/blog/tendances-tech-developpement-2026). Paradoxalement, cela renforce l'importance de bien maîtriser le développement : superviser du code exige de savoir en écrire soi-même, d'en reconnaître les bonnes pratiques et d'en repérer les défauts.</p>
      <h2 className="text-2xl font-semibold text-heading mt-8">Mes éléments de preuve</h2>
      <h3 className="text-xl font-semibold text-heading mt-6">Développer une To-Do App en Vue selon des bonnes pratiques définies en amont</h3>
      <p className="text-body leading-relaxed">Dans le cadre d'un <strong>projet personnel en cours</strong>, je développe une <strong>To-Do App en Vue</strong>. Sur ce projet, j'ai réalisé le cycle complet : j'ai d'abord analysé les besoins et conçu les solutions, puis j'ai <strong>implémenté les développements selon des bonnes pratiques que j'avais préalablement définies</strong> pour le projet.</p>
      <p className="text-body leading-relaxed">Concrètement, ce développement se caractérise par :</p>
      <p className="text-body leading-relaxed">- le <strong>respect d'un pattern donné</strong>, appliqué de manière cohérente dans toute l'application, ce qui structure le code et facilite sa compréhension ;</p>
      <p className="text-body leading-relaxed">- un <strong>code lisible</strong>, pensé pour être aisément compréhensible — par moi-même dans plusieurs mois comme par tout autre développeur ;</p>
      <p className="text-body leading-relaxed">- un code <strong>adapté aux nouveautés</strong> de l'écosystème Vue et du développement web moderne, plutôt que reposant sur des approches dépassées.</p>
      <p className="text-body leading-relaxed"><strong>Résultat et valeur ajoutée</strong> : l'application fonctionne conformément à la conception initiale et son code reste sain au fil des ajouts de fonctionnalités — preuve que les bonnes pratiques définies en amont portent leurs fruits. Ma valeur ajoutée réside dans la <strong>discipline de développement</strong> : plutôt que de coder au fil de l'eau, j'ai fixé mes règles avant d'écrire la première ligne, puis je m'y suis tenu. Ce projet me sert aussi de terrain d'entraînement à la maintenance : chaque bug rencontré est analysé, corrigé et devient un apprentissage.</p>
      <p className="text-body leading-relaxed">👉 [Voir la réalisation associée : To-Do App en Vue](#) *(lien vers la page de la réalisation)*</p>
      <h2 className="text-2xl font-semibold text-heading mt-8">Mon autocritique</h2>
      <p className="text-body leading-relaxed"><strong>Mon niveau de maîtrise</strong> : je considère <strong>maîtriser modestement cette compétence, avec une grande marge de progression</strong>, étant donné mon niveau <strong>junior</strong>. Cette lucidité est importante : je sais développer une solution fonctionnelle propre sur des périmètres que je connais, mais l'étendue des situations, des stacks et des types de bugs que je n'ai pas encore rencontrés est immense.</p>
      <p className="text-body leading-relaxed"><strong>Sa place dans mon profil</strong> : c'est le <strong>cœur opérationnel</strong> de mon métier de développeur web — la compétence qui transforme l'analyse et la conception en produit réel. Sans elle, les autres compétences restent théoriques. Elle occupe donc une place de premier plan dans mon profil, et c'est celle sur laquelle je passe le plus de temps au quotidien.</p>
      <p className="text-body leading-relaxed"><strong>Mon recul et mes conseils</strong> : ma conviction est que <strong>cette compétence ne s'acquiert que par l'expérience</strong> : il faut coder. Chaque pratique ou solution mise en place permet de <strong>découvrir de nouvelles choses</strong>, de <strong>faire face à de nouveaux bugs</strong> et de <strong>continuer d'apprendre</strong>. Il n'existe pas de raccourci théorique : on peut lire tous les livres sur le débogage, c'est en affrontant de vrais bugs qu'on apprend à déboguer. Mon conseil, pour moi-même comme pour les autres développeurs juniors : multiplier les projets, ne pas fuir les bugs difficiles — ce sont eux qui font le plus progresser — et considérer chaque erreur comme une leçon plutôt qu'un échec.</p>
      <h2 className="text-2xl font-semibold text-heading mt-8">Mon évolution dans cette compétence</h2>
      <p className="text-body leading-relaxed">Dans mon <strong>projet personnel et professionnel</strong>, mon objectif à moyen terme est de passer du niveau junior à un niveau de développeur <strong>confirmé et autonome</strong> : être capable de développer et de maintenir des solutions de complexité croissante, avec une qualité de code constante et une efficacité accrue dans la résolution de bugs.</p>
      <p className="text-body leading-relaxed"><strong>Le chemin est simple à énoncer et exigeant à suivre : continuer de coder et de faire des projets.</strong> Cette montée en compétence passe par mes projets d'alternance, qui me confrontent à du code de production réel avec ses contraintes et ses bugs, et par mes <strong>projets personnels</strong> — comme ma To-Do App en Vue — qui me permettent d'expérimenter librement de nouvelles pratiques, de nouvelles librairies et de nouveaux patterns. À cela s'ajoute une autoformation continue sur les évolutions de mes stacks (documentation, articles, veille), afin que mon code reste toujours « actuel », conformément à ma propre définition de cette compétence.</p>
    </article>
  );
}
